### ISSUE TITLE
Q: linux support?

### ISSUE THREAD

**Issue by negativeExponent** [gameblabla/sms_sdl#9]
i dunno if it was official, but i used to run in linux using Makefile to build the binary, despite output being a *.elf file. This seems to have been changed to something else instead of the sdl-related sources.

My question, was linux not intended to be supported at all? or is it being dropped.

**Comment by gameblabla** [comment]
Well the thing is Linux is supported but it's mostly used for testing. 
https://github.com/gameblabla/sms_sdl/commit/042dc4f2e688109a33dd4e8f767d8b1aa7c4fd3f

As you can see, i was testing the RS-90 frontend and somehow mistakenly pushed it to main... Ah well.
However if you were expecting a full SDL2 frontend for SMS Plus GX then it's not there yet. It is planned in the future once i get my RG-351P and perhaps make it more resolution-agnostic friendly along the way because SDL 1.2 is simply too slow for scaling so that's one of the reason why the "desktop" port is mostly used for testing.

**Comment by negativeExponent** [comment]
yeah thanks. linux port is now back working.

on a different note, are you interested in syncing changes with the libretro port? other than libretro-related changes, the change from C++ to CC comments would probably be a benefit at least. and if your have a need for C89 that would be possbile now when using standard maths in ym2143.c (since c89 do no have powf, logf, sinf etc)

**Comment by gameblabla** [comment]
I might be interested in syncing the other changes though i wouldn't too fond of the libretro-specific code as it would be pretty much me chasing me for the update and it's possible that i could be doing changes that you might not desire or wish to have. (although i try not to make game-breaking changes)
I'm mostly fine with C99 btw, i think that C89 might be a bit too limiting as it lacks restrict for example which is used for scaler.c unless we use the GNU specific extension.

For now i won't do anything as i have other stuff to deal with but i will consider it if your changes look interesting to me. (Stuff like EEPROM support or an LCD persistence filter for GG games)

**Comment by negativeExponent** [comment]
thanks for the reply. Yeah, there's is not much if not anything at all that i did internally. would have want ntsc filter baked and run on a per-line basis. but that would be better for another issue.

in anycase, as per this issue, its a done deal and thanks for the quick fix.
